/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AppVendasRouteImport } from './routes/_app.vendas'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppTrafegoPagoRouteImport } from './routes/_app.trafego-pago'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppReceitaProdutoRouteImport } from './routes/_app.receita-produto'
import { Route as AppMentoradosRouteImport } from './routes/_app.mentorados'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppIntegracoesRouteImport } from './routes/_app.integracoes'
import { Route as AppGastosRouteImport } from './routes/_app.gastos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContratosRouteImport } from './routes/_app.contratos'
import { Route as AppAplixFormKanbanRouteImport } from './routes/_app.aplix-form.kanban'
import { Route as AppAplixFormLeadsIndexRouteImport } from './routes/_app.aplix-form.leads.index'
import { Route as AppAplixFormFormsIndexRouteImport } from './routes/_app.aplix-form.forms.index'
import { Route as ApiPublicWebhooksSlugRouteImport } from './routes/api/public/webhooks/$slug'
import { Route as AppAplixFormLeadsIdRouteImport } from './routes/_app.aplix-form.leads.$id'
import { Route as AppAplixFormFormsIdRouteImport } from './routes/_app.aplix-form.forms.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTrafegoPagoRoute = AppTrafegoPagoRouteImport.update({
  id: '/trafego-pago',
  path: '/trafego-pago',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitaProdutoRoute = AppReceitaProdutoRouteImport.update({
  id: '/receita-produto',
  path: '/receita-produto',
  getParentRoute: () => AppRoute,
} as any)
const AppMentoradosRoute = AppMentoradosRouteImport.update({
  id: '/mentorados',
  path: '/mentorados',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppGastosRoute = AppGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppAplixFormKanbanRoute = AppAplixFormKanbanRouteImport.update({
  id: '/aplix-form/kanban',
  path: '/aplix-form/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppAplixFormLeadsIndexRoute = AppAplixFormLeadsIndexRouteImport.update({
  id: '/aplix-form/leads/',
  path: '/aplix-form/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppAplixFormFormsIndexRoute = AppAplixFormFormsIndexRouteImport.update({
  id: '/aplix-form/forms/',
  path: '/aplix-form/forms/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksSlugRoute = ApiPublicWebhooksSlugRouteImport.update({
  id: '/api/public/webhooks/$slug',
  path: '/api/public/webhooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAplixFormLeadsIdRoute = AppAplixFormLeadsIdRouteImport.update({
  id: '/aplix-form/leads/$id',
  path: '/aplix-form/leads/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAplixFormFormsIdRoute = AppAplixFormFormsIdRouteImport.update({
  id: '/aplix-form/forms/$id',
  path: '/aplix-form/forms/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/gastos': typeof AppGastosRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/leads': typeof AppLeadsRoute
  '/mentorados': typeof AppMentoradosRoute
  '/receita-produto': typeof AppReceitaProdutoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/trafego-pago': typeof AppTrafegoPagoRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas': typeof AppVendasRoute
  '/webhooks': typeof AppWebhooksRoute
  '/f/$slug': typeof FSlugRoute
  '/aplix-form/kanban': typeof AppAplixFormKanbanRoute
  '/aplix-form/forms/$id': typeof AppAplixFormFormsIdRoute
  '/aplix-form/leads/$id': typeof AppAplixFormLeadsIdRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/aplix-form/forms/': typeof AppAplixFormFormsIndexRoute
  '/aplix-form/leads/': typeof AppAplixFormLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contratos': typeof AppContratosRoute
  '/dashboard': typeof AppDashboardRoute
  '/gastos': typeof AppGastosRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/leads': typeof AppLeadsRoute
  '/mentorados': typeof AppMentoradosRoute
  '/receita-produto': typeof AppReceitaProdutoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/trafego-pago': typeof AppTrafegoPagoRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas': typeof AppVendasRoute
  '/webhooks': typeof AppWebhooksRoute
  '/f/$slug': typeof FSlugRoute
  '/aplix-form/kanban': typeof AppAplixFormKanbanRoute
  '/aplix-form/forms/$id': typeof AppAplixFormFormsIdRoute
  '/aplix-form/leads/$id': typeof AppAplixFormLeadsIdRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/aplix-form/forms': typeof AppAplixFormFormsIndexRoute
  '/aplix-form/leads': typeof AppAplixFormLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/contratos': typeof AppContratosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gastos': typeof AppGastosRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/mentorados': typeof AppMentoradosRoute
  '/_app/receita-produto': typeof AppReceitaProdutoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/trafego-pago': typeof AppTrafegoPagoRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/vendas': typeof AppVendasRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/f/$slug': typeof FSlugRoute
  '/_app/aplix-form/kanban': typeof AppAplixFormKanbanRoute
  '/_app/aplix-form/forms/$id': typeof AppAplixFormFormsIdRoute
  '/_app/aplix-form/leads/$id': typeof AppAplixFormLeadsIdRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/_app/aplix-form/forms/': typeof AppAplixFormFormsIndexRoute
  '/_app/aplix-form/leads/': typeof AppAplixFormLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contratos'
    | '/dashboard'
    | '/gastos'
    | '/integracoes'
    | '/leads'
    | '/mentorados'
    | '/receita-produto'
    | '/relatorios'
    | '/trafego-pago'
    | '/usuarios'
    | '/vendas'
    | '/webhooks'
    | '/f/$slug'
    | '/aplix-form/kanban'
    | '/aplix-form/forms/$id'
    | '/aplix-form/leads/$id'
    | '/api/public/webhooks/$slug'
    | '/aplix-form/forms/'
    | '/aplix-form/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contratos'
    | '/dashboard'
    | '/gastos'
    | '/integracoes'
    | '/leads'
    | '/mentorados'
    | '/receita-produto'
    | '/relatorios'
    | '/trafego-pago'
    | '/usuarios'
    | '/vendas'
    | '/webhooks'
    | '/f/$slug'
    | '/aplix-form/kanban'
    | '/aplix-form/forms/$id'
    | '/aplix-form/leads/$id'
    | '/api/public/webhooks/$slug'
    | '/aplix-form/forms'
    | '/aplix-form/leads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/contratos'
    | '/_app/dashboard'
    | '/_app/gastos'
    | '/_app/integracoes'
    | '/_app/leads'
    | '/_app/mentorados'
    | '/_app/receita-produto'
    | '/_app/relatorios'
    | '/_app/trafego-pago'
    | '/_app/usuarios'
    | '/_app/vendas'
    | '/_app/webhooks'
    | '/f/$slug'
    | '/_app/aplix-form/kanban'
    | '/_app/aplix-form/forms/$id'
    | '/_app/aplix-form/leads/$id'
    | '/api/public/webhooks/$slug'
    | '/_app/aplix-form/forms/'
    | '/_app/aplix-form/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FSlugRoute: typeof FSlugRoute
  ApiPublicWebhooksSlugRoute: typeof ApiPublicWebhooksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trafego-pago': {
      id: '/_app/trafego-pago'
      path: '/trafego-pago'
      fullPath: '/trafego-pago'
      preLoaderRoute: typeof AppTrafegoPagoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receita-produto': {
      id: '/_app/receita-produto'
      path: '/receita-produto'
      fullPath: '/receita-produto'
      preLoaderRoute: typeof AppReceitaProdutoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentorados': {
      id: '/_app/mentorados'
      path: '/mentorados'
      fullPath: '/mentorados'
      preLoaderRoute: typeof AppMentoradosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gastos': {
      id: '/_app/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AppGastosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos': {
      id: '/_app/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aplix-form/kanban': {
      id: '/_app/aplix-form/kanban'
      path: '/aplix-form/kanban'
      fullPath: '/aplix-form/kanban'
      preLoaderRoute: typeof AppAplixFormKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aplix-form/leads/': {
      id: '/_app/aplix-form/leads/'
      path: '/aplix-form/leads'
      fullPath: '/aplix-form/leads/'
      preLoaderRoute: typeof AppAplixFormLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aplix-form/forms/': {
      id: '/_app/aplix-form/forms/'
      path: '/aplix-form/forms'
      fullPath: '/aplix-form/forms/'
      preLoaderRoute: typeof AppAplixFormFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/$slug': {
      id: '/api/public/webhooks/$slug'
      path: '/api/public/webhooks/$slug'
      fullPath: '/api/public/webhooks/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/aplix-form/leads/$id': {
      id: '/_app/aplix-form/leads/$id'
      path: '/aplix-form/leads/$id'
      fullPath: '/aplix-form/leads/$id'
      preLoaderRoute: typeof AppAplixFormLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aplix-form/forms/$id': {
      id: '/_app/aplix-form/forms/$id'
      path: '/aplix-form/forms/$id'
      fullPath: '/aplix-form/forms/$id'
      preLoaderRoute: typeof AppAplixFormFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContratosRoute: typeof AppContratosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGastosRoute: typeof AppGastosRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMentoradosRoute: typeof AppMentoradosRoute
  AppReceitaProdutoRoute: typeof AppReceitaProdutoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTrafegoPagoRoute: typeof AppTrafegoPagoRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppAplixFormKanbanRoute: typeof AppAplixFormKanbanRoute
  AppAplixFormFormsIdRoute: typeof AppAplixFormFormsIdRoute
  AppAplixFormLeadsIdRoute: typeof AppAplixFormLeadsIdRoute
  AppAplixFormFormsIndexRoute: typeof AppAplixFormFormsIndexRoute
  AppAplixFormLeadsIndexRoute: typeof AppAplixFormLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContratosRoute: AppContratosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGastosRoute: AppGastosRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMentoradosRoute: AppMentoradosRoute,
  AppReceitaProdutoRoute: AppReceitaProdutoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTrafegoPagoRoute: AppTrafegoPagoRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVendasRoute: AppVendasRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppAplixFormKanbanRoute: AppAplixFormKanbanRoute,
  AppAplixFormFormsIdRoute: AppAplixFormFormsIdRoute,
  AppAplixFormLeadsIdRoute: AppAplixFormLeadsIdRoute,
  AppAplixFormFormsIndexRoute: AppAplixFormFormsIndexRoute,
  AppAplixFormLeadsIndexRoute: AppAplixFormLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FSlugRoute: FSlugRoute,
  ApiPublicWebhooksSlugRoute: ApiPublicWebhooksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
